import turtle
turtle.dot()
turtle.setheading(45)
turtle.forward(115)
turtle.dot()
turtle.goto(0,0)
turtle.setheading(315)
turtle.forward(115)
turtle.dot()
turtle.setheading(90)
turtle.forward(162)
turtle.penup()
turtle.goto(0,0)
turtle.pendown()
turtle.setheading(135)
turtle.forward(115)
turtle.dot()
turtle.goto(0,0)
turtle.setheading(225)
turtle.forward(115)
turtle.dot()
turtle.setheading(90)
turtle.forward(162)

turtle.setheading(360)
turtle.forward(10)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(40)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(40)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(13)

turtle.penup()
turtle.goto(-81,-81)


turtle.pendown()
turtle.forward(10)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(40)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(40)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(13)